# Generated by Django 5.1.4 on 2025-01-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/posts/images/'),
        ),
        migrations.AlterField(
            model_name='media',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/posts/videos/'),
        ),
    ]
