# Generated by Django 5.1.2 on 2025-01-13 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_user_remove_sender_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
    ]
