# Generated by Django 5.1.4 on 2024-12-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='uploads/profiles/gigachad.jpg', null=True, upload_to='uploads/profiles/'),
        ),
    ]
